language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install . --use-mirrors
  - pip install python-coveralls --use-mirrors
script:
  - coverage run --rcfile=coverage.rc -m unittest discover
after_success:
  - coveralls -c coverage.rc
